/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Clip {
  'startTrim' : number,
  'endTrim' : number,
  'name' : string,
  'durationSeconds' : number,
  'blobId' : string,
  'orderIndex' : bigint,
}
export interface Project {
  'activePreset' : string,
  'title' : string,
  'clips' : Array<Clip>,
  'createdAt' : bigint,
  'textOverlays' : Array<TextOverlay>,
  'updatedAt' : bigint,
}
export interface SubscriptionStatus {
  'plan' : string,
  'upgradeDate' : [] | [bigint],
}
export interface TextOverlay {
  'xPercent' : number,
  'color' : string,
  'text' : string,
  'yPercent' : number,
  'fontFamily' : string,
  'fontSize' : bigint,
}
export interface UserProfile {
  'displayName' : string,
  'createdAt' : bigint,
  'plan' : string,
  'totalUsageMinutes' : bigint,
  'projectCount' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProject' : ActorMethod<
    [string, Array<Clip>, Array<TextOverlay>, string],
    Project
  >,
  'deleteProject' : ActorMethod<[string], undefined>,
  'downgradeSubscription' : ActorMethod<[], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProject' : ActorMethod<[string], Project>,
  'getSubscriptionStatus' : ActorMethod<[], SubscriptionStatus>,
  'getUsageStats' : ActorMethod<
    [],
    { 'totalUsageMinutes' : bigint, 'projectCount' : bigint }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listFavoritePresets' : ActorMethod<[], Array<string>>,
  'listProjects' : ActorMethod<[], Array<Project>>,
  'removeFavoritePreset' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveFavoritePreset' : ActorMethod<[string], undefined>,
  'trackUsage' : ActorMethod<[bigint], undefined>,
  'updateProject' : ActorMethod<
    [string, string, Array<Clip>, Array<TextOverlay>, string],
    Project
  >,
  'updateUserProfile' : ActorMethod<[string], UserProfile>,
  'upgradeSubscription' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];