/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Clip = IDL.Record({
  'startTrim' : IDL.Float64,
  'endTrim' : IDL.Float64,
  'name' : IDL.Text,
  'durationSeconds' : IDL.Float64,
  'blobId' : IDL.Text,
  'orderIndex' : IDL.Nat,
});
export const TextOverlay = IDL.Record({
  'xPercent' : IDL.Float64,
  'color' : IDL.Text,
  'text' : IDL.Text,
  'yPercent' : IDL.Float64,
  'fontFamily' : IDL.Text,
  'fontSize' : IDL.Nat,
});
export const Project = IDL.Record({
  'activePreset' : IDL.Text,
  'title' : IDL.Text,
  'clips' : IDL.Vec(Clip),
  'createdAt' : IDL.Int,
  'textOverlays' : IDL.Vec(TextOverlay),
  'updatedAt' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'createdAt' : IDL.Int,
  'plan' : IDL.Text,
  'totalUsageMinutes' : IDL.Nat,
  'projectCount' : IDL.Nat,
});
export const SubscriptionStatus = IDL.Record({
  'plan' : IDL.Text,
  'upgradeDate' : IDL.Opt(IDL.Int),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProject' : IDL.Func(
      [IDL.Text, IDL.Vec(Clip), IDL.Vec(TextOverlay), IDL.Text],
      [Project],
      [],
    ),
  'deleteProject' : IDL.Func([IDL.Text], [], []),
  'downgradeSubscription' : IDL.Func([], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProject' : IDL.Func([IDL.Text], [Project], ['query']),
  'getSubscriptionStatus' : IDL.Func([], [SubscriptionStatus], ['query']),
  'getUsageStats' : IDL.Func(
      [],
      [IDL.Record({ 'totalUsageMinutes' : IDL.Nat, 'projectCount' : IDL.Nat })],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listFavoritePresets' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'removeFavoritePreset' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveFavoritePreset' : IDL.Func([IDL.Text], [], []),
  'trackUsage' : IDL.Func([IDL.Nat], [], []),
  'updateProject' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(Clip), IDL.Vec(TextOverlay), IDL.Text],
      [Project],
      [],
    ),
  'updateUserProfile' : IDL.Func([IDL.Text], [UserProfile], []),
  'upgradeSubscription' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Clip = IDL.Record({
    'startTrim' : IDL.Float64,
    'endTrim' : IDL.Float64,
    'name' : IDL.Text,
    'durationSeconds' : IDL.Float64,
    'blobId' : IDL.Text,
    'orderIndex' : IDL.Nat,
  });
  const TextOverlay = IDL.Record({
    'xPercent' : IDL.Float64,
    'color' : IDL.Text,
    'text' : IDL.Text,
    'yPercent' : IDL.Float64,
    'fontFamily' : IDL.Text,
    'fontSize' : IDL.Nat,
  });
  const Project = IDL.Record({
    'activePreset' : IDL.Text,
    'title' : IDL.Text,
    'clips' : IDL.Vec(Clip),
    'createdAt' : IDL.Int,
    'textOverlays' : IDL.Vec(TextOverlay),
    'updatedAt' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'createdAt' : IDL.Int,
    'plan' : IDL.Text,
    'totalUsageMinutes' : IDL.Nat,
    'projectCount' : IDL.Nat,
  });
  const SubscriptionStatus = IDL.Record({
    'plan' : IDL.Text,
    'upgradeDate' : IDL.Opt(IDL.Int),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProject' : IDL.Func(
        [IDL.Text, IDL.Vec(Clip), IDL.Vec(TextOverlay), IDL.Text],
        [Project],
        [],
      ),
    'deleteProject' : IDL.Func([IDL.Text], [], []),
    'downgradeSubscription' : IDL.Func([], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProject' : IDL.Func([IDL.Text], [Project], ['query']),
    'getSubscriptionStatus' : IDL.Func([], [SubscriptionStatus], ['query']),
    'getUsageStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalUsageMinutes' : IDL.Nat,
            'projectCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listFavoritePresets' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'removeFavoritePreset' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveFavoritePreset' : IDL.Func([IDL.Text], [], []),
    'trackUsage' : IDL.Func([IDL.Nat], [], []),
    'updateProject' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(Clip), IDL.Vec(TextOverlay), IDL.Text],
        [Project],
        [],
      ),
    'updateUserProfile' : IDL.Func([IDL.Text], [UserProfile], []),
    'upgradeSubscription' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };